### ISSUE TITLE
No instructions mentioned for CLI calling from Windows in readme.md 

### ISSUE THREAD

**Issue by Rahuljagwani** [ControlCore-Project/concore-lite#1]
For now, instructions are given for unix based systems only i.e. Linux and MacOS.
If someone wants to use it from window, following text should be added.

" To run on Windows just replace './COMMAND' by 'COMMAND' . Example: In place of 
calling ' ./makestudy example/sampleplot.graphml '  call 'makestudy example/sampleplot.graphml' ."

**Comment by pradeeban** [comment]
Sounds good. Please send a PR to the README with your proposed text.
